const vars = {
  OTPExpirationDurationInSeconds: 200000,
  TokenExpirationDurationInSeconds: 500000,
  saltRounds: 10,
};

const routes = {
  SIGN_UP: "/auth/sign-up",
  SIGN_IN: "/auth/sign-in",
  FORGOT_PASSWORD: "/auth/forgot-password",
  VOTP: "/auth/votp",
  FOTP: "/auth/fotp",
  VERIFY_TOKEN: "/verify-token",
  CONTRIBUTE: "/contribute",
  ACCOUNT_INTERVIEW_EXPERIENCES: "/account/interview-experiences",
  INTERVIEW_EXPERIENCES: "/interview-experiences",
  READ: "/interview-experience/read",
  PARTICULAR_INTERVIEW_EXPERIENCE: "/particular-interview-experience",
};

const statusText = {
  SIGN_IN_SUCCESS: "You have been signed in successfully",
  SIGN_IN_FAIL: "We were to unable to sign you in. Please try again",
  SIGN_UP_SUCCESS: "You have been signed up successfully",
  SIGN_UP_FAIL: "We were to unable to sign you up. Please try again",
  USER_NOT_FOUND: "We were to unable to find any user with these credentials",
  USER_EMAIL_EXISTS: "A user with this Email Address already exists",
  OTP_VERIFICATION_FAIL: "We were unable to verify the OTP. Please try again",
  OTP_NOT_OURS: "The OTP that you have entered was not generated by us",
  OTP_EXPIRED: "OTP has been expired",
  OTP_WRONG: "You have entered a wrong OTP",
  SOMETHING_WENT_WRONG: "Something went wrong, Please try again",
  NOT_AUTHORIZED: "You're not authorized to see this page. Please sign in",
  TOKEN_INVALID_CANNOT_CONTRIBUTE:
    "You're not signed in. Please sign in to contribute",
  TOKEN_INVALID_CANNOT_DISPLAY_ACCOUNT:
    "You're not signed in. Please sign in to see your account information",
  ACCOUNT_FETCH_FAILED:
    "We were unable to fetch your account information. Please try again",
  ACCOUNT_NOT_FOUND:
    "We were unable to find any account associated with this Email address",
  TOKEN_EXPIRED: "The session has expired. Please sign in again",
  TOKEN_VERIFIED: "You're are already signed in",
  CONTRIBUTION_SUCCESS: "Your contribution has been added successfully",
  CONTRIBUTION_FAILED:
    "We were unable to add your contribution. Please try again",
  INTERVIEW_EXPERIENCES_NOT_FOUND:
    "We were unable to fetch any interview experiences. Please visit this section after sometime",
  INTERVIEW_EXPERIENCES_FOUND:
    "All the interview experiences were fetched successfully",
  INTERVIEW_EXPERIENCE_NOT_FOUND:
    "We were unable to fetch the interview experience. Please visit this section after sometime",
  INTERVIEW_EXPERIENCE_FOUND:
    "The interview experience was fetched successfully",
  UNABLE_TO_FIND_RESOURCE:
    "We were unable to fulfill the request. Please try again later",
};

module.exports = {
  routes,
  vars,
  statusText,
};
